name: ci

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: kellerkinder/ci:{{ matrix.php }}
          build-args: |
            PHP_VERSION={{ matrix.php }}
      -
        name: Test
        run: |
          docker run --rm kellerkinder/ci:{{ matrix.php }}
      -
        name: Push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kellerkinder/ci:{{ matrix.php }}
          build-args: |
            PHP_VERSION={{ matrix.php }}
