name: ci

on:
  schedule:
    - cron: '0 10 * * *' # every day at 10am
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: edbizarro/gitlab-ci-pipeline-php:{{ matrix.php }}
          image: pipeline-image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: pipeline-image:{{ matrix.php }}
          build-args: |
            PHP_VERSION={{ matrix.php }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Test
        run: |
          docker run --rm pipeline-image:{{ matrix.php }}
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
      - name: Push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pipeline-image:{{ matrix.php }}
          build-args: |
            PHP_VERSION={{ matrix.php }}

        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
